### ISSUE TITLE
Setup integration tests for coursectl 

### ISSUE THREAD

**Issue by anandology** [fossunited/coursectl#6]
Have integration tests, that will start a new instance of community app locally and run tests against that. 

The tests should cover all the possible use cases.

## Tasks
- [ ] create a docker-image frappe-test-school that with bench instance and a site school.localhost and fixed api keys
- [ ] create a docker-image frappe-test-school-db based on mariadb with all the data of test school and a sample course
- [ ] write tests for each command
